export const ErrorTypeMappings = {
      NO_ZAPR_DATA: "NO_ZAPR_DATA",
      NO_GAT_INSIGHTS_FILTER: "NO_GAT_INSIGHTS_FILTER",
      NO_POST_LOGIN: "NO_POST_LOGIN",
      NO_SHOWS_BY_NAME: "NO_SHOWS_BY_NAME",
      NO_ALL_STATES_AND_DISTRICTS: "NO_ALL_STATES_AND_DISTRICTS"
}