
/* ---------------------------------------------- MATERIAL LIBRARY -------------------------------------------- */
// Export Packaged Modules from Material Library
export {
        Box,
        Fab,
        Tab,
        Tabs,
        Chip,
        Card,
        Menu,
        List,
        Grid,
        Paper,
        Badge,
        Slide,
        Switch,
        Dialog,
        Select,
        Avatar,
        Slider,
        Button,
        AppBar,
        Drawer,
        Tooltip,
        SvgIcon,
        Toolbar,
        Divider,
        Popover,
        MenuList,
        Collapse,
        MenuItem,
        Checkbox,
        ListItem,
        Snackbar,
        CardMedia,
        InputBase,
        TextField,
        withStyles,
        Typography,
        IconButton,
        CardContent,
        CssBaseline,
        FormControl,
        ListItemText,
        ListItemIcon,
        ListSubheader,
        CardActionArea,
        LinearProgress,
        SwipeableDrawer,
        Unstable_TrapFocus,
} from '@material-ui/core';

export {
        Alert,
        TabList,
        TabPanel,
        TabContext,
        ToggleButton,
        Autocomplete,
        ToggleButtonGroup,
} from '@material-ui/lab';

export {
        fade,
        useTheme,
        makeStyles,
} from '@material-ui/core/styles';

export {
        AddRounded,
        DoneRounded,
        ChatRounded,
        MailRounded,
        MenuRounded,
        CloseRounded,
        TodayRounded,
        ImageRounded,
        SearchRounded,
        PublicRounded,
        BlurOnRounded,
        GetAppRounded,
        CompareRounded,
        ListAltRounded,
        CheckBoxRounded,
        FeedbackRounded,
        TouchAppRounded,
        GroupAddRounded,
        BookmarkRounded,
        DeviceHubRounded,
        DataUsageRounded,
        VisibilityRounded,
        AccessTimeRounded,
        MotorcycleRounded,
        ExpandMoreRounded,
        LowPriorityRounded,
        Brightness2Rounded,
        AddToPhotosRounded,
        Brightness7Rounded,
        DescriptionRounded,
        Brightness3Rounded,
        ErrorOutlineRounded,
        AccountTreeRounded,
        TrackChangesRounded,
        PhotoLibraryRounded,
        CalendarTodayRounded,
        CompareArrowsRounded,
        AccountCircleRounded,
        NotificationsRounded,
        SettingsVoiceRounded,
        ShoppingBasketRounded,
        ArrowForwardIosRounded,
        SystemUpdateAltRounded,
        InsertDriveFileRounded,
        CheckBoxOutlineBlankRounded,
} from '@material-ui/icons';
